/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evaluaciondowhile;

import javax.swing.JOptionPane;

/**
 *
 * @author Daniel C
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        viewResultado = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewResultado.setColumns(20);
        viewResultado.setRows(5);
        jScrollPane1.setViewportView(viewResultado);

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Calculo de Notas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel5))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addGap(169, 169, 169))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String res, nombre, n1, n2, n3;
        Double def;
        Double promedio;
        int i=0;
        do {
            
            nombre = JOptionPane.showInputDialog(this, "Nombre");
            n1 = JOptionPane.showInputDialog(this, "Nota1");
            n2 = JOptionPane.showInputDialog(this, "Nota2");
            n3 = JOptionPane.showInputDialog(this, "Nota3");

            Double nota1 = Double.parseDouble(n1);
            Double nota2 = Double.parseDouble(n2);
            Double nota3 = Double.parseDouble(n3);

            def = (nota1 * 0.3) + (nota2 * 0.3) + (nota3 * 0.4);
            res = JOptionPane.showInputDialog(this, "Otro");
            

            JOptionPane.showMessageDialog(this, "\n" + "Nombre: " + nombre + "\n"
                    + "Nota 1: " + nota1 + "\n"
                    + "Nota 2: " + nota2 + "\n"
                    + "Nota 3: " + nota3 + "\n"
                    + "Definitiva: " + def + "\n"
                    );

            viewResultado.setText(viewResultado.getText() + "\n" + "Nombre: " + nombre + "\n"
                    + "Nota 1: " + nota1 + "\n"
                    + "Nota 2: " + nota2 + "\n"
                    + "Nota 3: " + nota3 + "\n"
                    + "Definitiva: " + def + "\n"
                   
            );
            i++;
            def++;

        } while (res.equals("S"));
        promedio=def/i;
        viewResultado.setText(viewResultado.getText()+"Promedio Salon"+promedio);
        
        
        


        
        /*
        String nombre = txtNombre.getText();
        double nota1 = Double.parseDouble(txtN1.getValue().toString());
        double nota2 = Double.parseDouble(txtN2.getValue().toString());
        double nota3 = Double.parseDouble(txtN3.getValue().toString());
        double promSalon = 0;
        double res;
        String con;

        do {
            txtNombre.setText("");
            txtN1.setValue(0);
            txtN2.setValue(0);
            txtN3.setValue(0);

            res = (nota1 * 0.3) + (nota2 * 0.3) + (nota3 * 0.4);
            promSalon = res++;

            viewResultado.setText(viewResultado.getText() + "\n" + "Nombre: " + nombre + "\n"
                    + "Nota 1: " + nota1 + "\n"
                    + "Nota 2: " + nota2 + "\n"
                    + "Nota 3: " + nota3 + "\n"
                    + "Definitiva: " + res + "\n"
                    + "Promedio salon: " + promSalon + "\n"
            );
            txtNombre.setText("");
            txtN1.setValue(0);
            txtN2.setValue(0);
            txtN3.setValue(0);

            con = JOptionPane.showInputDialog("Otro Usuario");

        } while (con.equals("S"));
*/
        


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea viewResultado;
    // End of variables declaration//GEN-END:variables
}
